services:
  scrape:
    build: .
    command: "java -jar /app/target/scala-2.13/scraper.jar scrape"
    volumes:
      - ./${DB}:/db
  render:
    build: .
    command: "java -jar /app/target/scala-2.13/scraper.jar render"
    volumes:
      - ./${DB}:/db
      - ./${RENDER}:/render